    version: '3.5'
    
    services:
      postgres:
        image: postgis/postgis
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          PGDATA: /data/postgres
        volumes:
          - ./data/postgis:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        restart: always
